Projet : SourceRenMairlot.o fctplateau.o fctinsertion.o fctpartie.o
	gcc -o Projet SourceRenMairlot.o fctplateau.o fctinsertion.o fctpartie.o

SourceRenMairlot.o : SourceRenMairlot.c 
	gcc -Wall -c SourceRenMairlot.c 

fctplateau.o : fctplateau.c
	gcc -Wall -c fctplateau.c

fctinsertion.o : fctinsertion.c
	gcc -Wall -c fctinsertion.c

fctpartie.o : fctpartie.c
	gcc -Wall -c fctpartie.c
